Added mentions and company models
hatchways/team-sapphire pull request #46
Opened 2019-12-01 19:51 UTC by derekjou

Modified settings to refer to company model, which was newly added. The company document will reference mention documents.

2019-12-02 02:04 UTC, ncen5293 commented
When I make a new account, it makes a user document then crashes the backend and is unable to make a user settings document.
You would also have to change how we get and set companies 
![image](https://user-images.githubusercontent.com/28994838/69925370-cf52d080-147d-11ea-9400-e81c1e5981c2.png)

2019-12-02 05:17 UTC, derekjou commented
> When I make a new account, it makes a user document then crashes the backend and is unable to make a user settings document.
> You would also have to change how we get and set companies
> ![image](https://user-images.githubusercontent.com/28994838/69925370-cf52d080-147d-11ea-9400-e81c1e5981c2.png)

Fixed! I won't be able to integrate the mentions model fully yet until we get the OK from Aecio on the interface. Reddit and Twitter routes will have to be modified for this as well later!

2019-12-03 03:25 UTC, ncen5293 reviewed
Everything looks good except you could just merge dev into this branch and in the /:email route just get the companies the same way you did with /:email/company for using the interface and giving the company names to the frontend

2019-12-03 17:31 UTC, ncen5293 requested changes

2019-12-03 17:31 UTC, ncen5293 commented on server/routes/settings.js
> +      const mentions = await interface.getNewestMentions(companyNames);
can you also make it an async route since it is using await?
and can you pass the companyNames to the frontend too

2019-12-03 18:45 UTC, merged